# -*- coding: utf-8 -*-
"""33

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W6tOdDcA_2wqBRaF3vbsJKAGMVCOsBDn
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("day33_corr.csv")

corr = df.corr(numeric_only=True)

plt.figure()
sns.heatmap(corr, annot=True, vmin=-1, vmax=1, cmap="coolwarm")
plt.title("Correlation Matrix for Numeric Features")
plt.show()