# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd

train = pd.DataFrame({
    "age": [25, None, 40, 33],
    "city": ["NY", "SF", None, "NY"],
})

test = pd.DataFrame({
    "age": [None, 50],
    "city": ["SF", None],
})

def fit_imputer(train_df, num_cols, cat_cols):
    params = {}

    for col in num_cols:
        params[col] = train_df[col].median()

    for col in cat_cols:
        params[col] = train_df[col].mode()[0]

    return params


def transform_imputer(df, params, add_indicators=True):
    df_copy = df.copy()

    for col in params:

        if add_indicators:
            df_copy[col + "_missing"] = df_copy[col].isna().astype(int)

        df_copy[col] = df_copy[col].fillna(params[col])

    return df_copy


num_cols = ["age"]
cat_cols = ["city"]

params = fit_imputer(train, num_cols, cat_cols)

train_with_ind = transform_imputer(train, params, True)
test_with_ind = transform_imputer(test, params, True)

train_no_ind = transform_imputer(train, params, False)

print("Train with indicators")
print(train_with_ind)

print("\nTest with indicators")
print(test_with_ind)

print("\nTrain without indicators")
print(train_no_ind)