# -*- coding: utf-8 -*-
"""assignment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXtFNrAQRQFpqjYwH6J3OJnh3LDDsGve
"""

cat_a = [1, 2, 3, 4, 5]
cat_b = [10, 20, 30]

def calculate_stats(data):
    mean = sum(data) / len(data)
    maximum = max(data)
    return {"mean": mean, "max": maximum}

stats_a = calculate_stats(cat_a)
stats_b = calculate_stats(cat_b)

print("A:", stats_a)
print("B:", stats_b)

from typing import List, Dict, Tuple
import math

def calculate_statistics(data: List[float]) -> Dict[str, float]:
    """Return basic statistics: mean, min, max."""
    if len(data) == 0:
        raise ValueError("data must not be empty")

    mean = sum(data) / len(data)
    return {
        "mean": mean,
        "min": min(data),
        "max": max(data)
    }

def normalize_data(data: List[float], method: str = "minmax") -> List[float]:
    """
    Normalize data:
    - minmax: scales values to [0, 1]
    - zscore: (x - mean) / std
    """
    if len(data) == 0:
        return []

    if method not in ("minmax", "zscore"):
        raise ValueError("method must be 'minmax' or 'zscore'")

    if method == "minmax":
        mn = min(data)
        mx = max(data)
        if mx == mn:
            return [0.0 for _ in data]
        return [(x - mn) / (mx - mn) for x in data]

    # zscore
    mean = sum(data) / len(data)
    variance = sum((x - mean) ** 2 for x in data) / len(data)
    std = math.sqrt(variance)
    if std == 0:
        return [0.0 for _ in data]
    return [(x - mean) / std for x in data]

def remove_outliers(data: List[float], threshold: float) -> List[float]:
    """
    Remove outliers using rule:
    keep x if abs(x - mean) <= threshold * std
    """
    if len(data) == 0:
        return []
    if threshold <= 0:
        raise ValueError("threshold must be > 0")

    mean = sum(data) / len(data)
    variance = sum((x - mean) ** 2 for x in data) / len(data)
    std = math.sqrt(variance)

    if std == 0:
        return data[:]

    return [x for x in data if abs(x - mean) <= threshold * std]

def train_test_split(data: List[float], ratio: float = 0.8) -> Tuple[List[float], List[float]]:
    """Split list into train and test parts based on ratio."""
    if not (0 < ratio < 1):
        raise ValueError("ratio must be between 0 and 1")

    split = int(len(data) * ratio)
    return data[:split], data[split:]

def encode_labels(labels: List[str]) -> Dict[str, int]:
    """Map each unique label to an integer id starting from 0."""
    mapping: Dict[str, int] = {}
    for label in labels:
        if label not in mapping:
            mapping[label] = len(mapping)
    return mapping

# ---- Small Tests ----
print("\n--- Activity 2 Tests ---")
nums = [1, 2, 3, 100]
print("calculate_statistics:", calculate_statistics(nums))
print("normalize_data minmax:", normalize_data(nums, "minmax"))
print("normalize_data zscore:", normalize_data(nums, "zscore"))
print("remove_outliers threshold=1.0:", remove_outliers(nums, 1.0))

train, test = train_test_split(nums, 0.75)
print("train_test_split 0.75:", "train=", train, "test=", test)

print("encode_labels:", encode_labels(["apple", "banana", "apple", "orange"]))

import pandas as pd

# Sample dataset
raw = {
   "product": ["Widget A", "Widget B", "Widget C"],
   "price": ["$1,234.50", "$567.89", "$2,345.00"],
   "quantity": [10, 5, None],
}

df = pd.DataFrame(raw)

# 1) Clean price (remove $ and commas) using apply + lambda
df["price"] = df["price"].apply(
    lambda x: float(x.replace("$", "").replace(",", ""))
)

# 2) Fill missing quantity with 0
df["quantity"] = df["quantity"].fillna(0)

# 3) Create total = price * quantity
df["total"] = df["price"] * df["quantity"]

# 4) Categorize price: low / med / high
df["price_category"] = df["price"].apply(
    lambda p: "low" if p < 700 else ("med" if p < 1500 else "high")
)

# Show result
print(df)