# -*- coding: utf-8 -*-
"""assignment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXtFNrAQRQFpqjYwH6J3OJnh3LDDsGve
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("day34_patterns.csv")

g = sns.relplot(
    data=df,
    x=df.columns[0],
    y=df.columns[1],
    hue=df.columns[2] if len(df.columns) > 2 else None,
    col=df.columns[3] if len(df.columns) > 3 else None,
    row=df.columns[4] if len(df.columns) > 4 else None,
    kind="scatter"
)

sns.lmplot(
    data=df,
    x=df.columns[0],
    y=df.columns[1],
    hue=df.columns[2] if len(df.columns) > 2 else None,
    col=df.columns[3] if len(df.columns) > 3 else None,
    row=df.columns[4] if len(df.columns) > 4 else None,
    scatter=False
)

plt.show()