# -*- coding: utf-8 -*-
"""assignment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXtFNrAQRQFpqjYwH6J3OJnh3LDDsGve
"""

import pandas as pd
import numpy as np
from sklearn.feature_selection import VarianceThreshold

np.random.seed(42)
data_size = 50

X = pd.DataFrame({
    'feature_1': np.random.rand(data_size),
    'feature_2': np.random.rand(data_size),
    'feature_3': np.random.rand(data_size) * 0.01,
    'feature_4': np.random.rand(data_size),
    'feature_5': np.random.rand(data_size),
    'feature_6': np.linspace(0, 1, data_size)
})

y = X['feature_1'] * 2 + X['feature_2'] * 3 + np.random.randn(data_size)

selector = VarianceThreshold(threshold=0.01)
X_high_var = selector.fit_transform(X)
X_high_var = pd.DataFrame(X_high_var, columns=X.columns[selector.get_support()])

print("Columns after removing low variance features:")
print(X_high_var.columns.tolist())

corr_matrix = X_high_var.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
to_drop = [col for col in upper.columns if any(upper[col] > 0.9)]
X_selected = X_high_var.drop(columns=to_drop)

print("\nColumns after removing highly correlated features:")
print(X_selected.columns.tolist())

print(f"\nNumber of columns before: {X.shape[1]}")
print(f"Number of columns after Feature Selection: {X_selected.shape[1]}")