# -*- coding: utf-8 -*-
"""assignment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXtFNrAQRQFpqjYwH6J3OJnh3LDDsGve
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

np.random.seed(42)
X = np.linspace(0, 10, 20).reshape(-1, 1)
y = 0.5 * X.flatten()**2 + X.flatten() + np.random.randn(20)

df = pd.DataFrame({'x': X.flatten(), 'y': y})

degrees = [1, 2, 5]
models = {}

for d in degrees:
    poly = PolynomialFeatures(degree=d)
    X_poly = poly.fit_transform(X)
    model = LinearRegression()
    model.fit(X_poly, y)
    models[d] = model

plt.scatter(X, y, color='black', label='Data')
x_range = np.linspace(X.min(), X.max(), 100).reshape(-1, 1)

for d in degrees:
    poly = PolynomialFeatures(degree=d)
    y_pred = models[d].predict(poly.fit_transform(x_range))
    plt.plot(x_range, y_pred, label=f'Degree {d}')

plt.xlabel('X')
plt.ylabel('y')
plt.title('Polynomial Regression Comparison')
plt.legend()
plt.show()