# -*- coding: utf-8 -*-
"""assignment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXtFNrAQRQFpqjYwH6J3OJnh3LDDsGve
"""

import pandas as pd
import numpy as np

df = pd.read_csv("data/day21_housing.csv")

df["price_per_sqft"] = np.where(
    df["sqft"] > 0,
    df["price"] / df["sqft"],
    np.nan
)

df["price_per_bedroom"] = np.where(
    df["bedrooms"] > 0,
    df["price"] / df["bedrooms"],
    np.nan
)

df["bedrooms_per_sqft"] = np.where(
    df["sqft"] > 0,
    df["bedrooms"] / df["sqft"],
    np.nan
)

print("=== Basic Features Summary ===")
print(df[["price", "sqft", "bedrooms"]].describe())

print("\n=== With Domain Features Summary ===")
print(df[[
    "price_per_sqft",
    "price_per_bedroom",
    "bedrooms_per_sqft"
]].describe())

import pandas as pd

df = pd.read_csv("data/day22_interactions.csv")

df['mul_ab'] = df['feature_a'] * df['feature_b']
df['add_ab'] = df['feature_a'] + df['feature_b']
df['logical_ab'] = (df['feature_a'] > 0) & (df['feature_b'] > 0)

correlations = df.corr()['target'].sort_values(ascending=False)
print(correlations)