# -*- coding: utf-8 -*-
"""assignment 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BuZMwJ89_tWvb-UAEHS4BZQftlKQUOM

Tasks:
"""

students = {"S001":
   {"name": "Alice Chen",
    "courses": {"CS101": {"grade": 92, "credits": 3},
     "MATH201": {"grade": 88, "credits": 4},
      "AI301": {"grade": 95, "credits": 3},},
       "advisor": "Dr. Smith",}

        ,"S002": {"name": "Bob Lee","courses":
         {"CS101": {"grade": 85, "credits": 3}
          ,"MATH201": {"grade": 90, "credits": 4},},
           "advisor": "Dr. Patel",},}

"""Get Alice's AI301 grade"""

alice_grade=students["S001"]["courses"]["AI301"]["grade"]
print(alice_grade)

"""Get average grade across all courses"""

total_grades = 0
course_count = 0

for student in students.values():
    for course in student["courses"].values():
        total_grades += course["grade"]
        course_count += 1

average = total_grades / course_count

print("Average grade:", average)

"""Find student with highest GPA
Calculate Bob's GPA (weighted by credits)
"""

student_gpas = {}

for student_id, student in students.items():
    courses = student["courses"]
    total_credits = sum(c["credits"] for c in courses.values())
    weighted_sum = sum(c["grade"] * c["credits"] for c in courses.values())
    gpa = weighted_sum / total_credits
    student_gpas[student["name"]] = gpa


print(student_gpas)
print("Bob GPA:", student_gpas["Bob Lee"])

highest_student = max(student_gpas, key=student_gpas.get)
print("Highest GPA:", highest_student)

"""Find all students in CS101"""

cs101_students = []

for student_id, info in students.items():
    if "CS101" in info["courses"]:
        cs101_students.append(info["name"])

print(cs101_students)

"""Day 5 Activity: JSON + File Handling mini workflow."""

import json
from pathlib import Path

config_path = Path("config.json")

if not config_path.exists():
    default_config = {
        "epochs": 10,
        "learning_rate": 0.01,
        "batch_size": 32
    }

    with open(config_path, "w") as file:
        json.dump(default_config, file, indent=4)

with open(config_path, "r") as file:
    config = json.load(file)

print("Config values")
print(config)

results = {
    "accuracy": 0.85,
    "loss": 0.32,
    "epochs": config.get("epochs")
}

results_path = Path("results.json")

with open(results_path, "w") as file:
    json.dump(results, file, indent=4)

print("Results saved successfully")