# -*- coding: utf-8 -*-
"""assignment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXtFNrAQRQFpqjYwH6J3OJnh3LDDsGve
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


df = pd.read_csv("day31_seaborn.csv")

sns.histplot(df, x="income", bins=20)
plt.title("Income histplot")
plt.show()

sns.kdeplot(df["age"], fill=True)
plt.title("Age KDE")
plt.show()

sns.boxplot(x="segment", y="income", data=df)
plt.title("Income by Segment")
plt.show()

sns.countplot(x="segment", data=df)
plt.title("Segment counts")
plt.show()