# -*- coding: utf-8 -*-
"""assignment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXtFNrAQRQFpqjYwH6J3OJnh3LDDsGve
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

file_path = "data/day31_seaborn.csv"

if os.path.exists(file_path):
    df = pd.read_csv(file_path)
else:
    df = pd.DataFrame({
        "value": [10, 20, 15, 30, 25, 40, 35, 50, 60, 45],
        "category": ["A", "B", "A", "B", "C", "C", "B", "A", "C", "B"]
    })

print(df.head())

plt.figure(figsize=(8,4))
sns.histplot(df['value'], bins=5, kde=False)
plt.title("Histogram")
plt.show()

plt.figure(figsize=(8,4))
sns.kdeplot(df['value'], shade=True)
plt.title("KDE Plot")
plt.show()

plt.figure(figsize=(6,4))
sns.boxplot(x=df['value'])
plt.title("Boxplot")
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x=df['category'])
plt.title("Countplot")
plt.show()