# -*- coding: utf-8 -*-
"""Linear Regression-Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9DmYjHhZ27vV4OrZD-5lZFKxB5ashK9
"""

import numpy as np

# Provided vectors
a = np.array([1.0, 2.0, 3.0])
b = np.array([0.5, 1.0, 1.5])

# Compute dot product
dot = np.dot(a, b)

# Compute norms
norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)

# Compute cosine similarity
cos_sim = dot / (norm_a * norm_b)

# Print results
print("Dot product:", dot)
print("Cosine similarity:", cos_sim)