# -*- coding: utf-8 -*-
"""Linear Regression-Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9DmYjHhZ27vV4OrZD-5lZFKxB5ashK9
"""

import numpy as np

# Provided vectors
feature = np.array([30.0, 50.0, 10.0])
weights = np.array([0.05, 0.8, -0.1])

# Vector addition
addition = feature + weights

# Scalar multiplication
scaled_feature = 2 * feature

# Compute norms
feature_norm = np.linalg.norm(feature)
weights_norm = np.linalg.norm(weights)

# Print results
print("Vector addition:", addition)
print("Scaled feature:", scaled_feature)

print("Feature norm:", feature_norm)
print("Weights norm:", weights_norm)

print("feature shape:", feature.shape)
print("weights shape:", weights.shape)