# -*- coding: utf-8 -*-
"""assignment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXtFNrAQRQFpqjYwH6J3OJnh3LDDsGve
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("day35_project (1).csv")

num_cols = df.select_dtypes(include="number").columns

plt.figure()
sns.histplot(df[num_cols[0]], kde=True)

plt.figure()
sns.histplot(df[num_cols[1]], kde=True)

plt.figure()
sns.histplot(df[num_cols[2]], kde=True)

plt.figure()
sns.scatterplot(x=num_cols[0], y=num_cols[1], data=df)

plt.figure()
sns.heatmap(df[num_cols].corr(), annot=True, cmap="coolwarm")

plt.show()

from google.colab import drive
drive.mount('/content/drive')