# -*- coding: utf-8 -*-
"""Day 10 Activity: Outliers Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WLHJ3nYLjkhCEE2KAi_pnLAqcOVwCwMM
"""

import numpy as np
import pandas as pd

np.random.seed(10)
values = np.concatenate([np.random.lognormal(10, 0.5, 1000), [1e7, 2e7]])

df = pd.DataFrame({"income": values})

def iqr_bounds(series):
    Q1 = series.quantile(0.25)
    Q3 = series.quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return lower, upper


def detect_outliers_iqr(series):
    lower, upper = iqr_bounds(series)
    return (series < lower) | (series > upper)

def detect_outliers_zscore(series, threshold=3):
    mean = series.mean()
    std = series.std()
    z_scores = (series - mean) / std
    return np.abs(z_scores) > threshold

df["original"] = df["income"]

lower, upper = iqr_bounds(df["income"])
df["iqr_capped"] = df["income"].clip(lower, upper)

df["log1p"] = np.log1p(df["income"])

df["iqr_outlier"] = detect_outliers_iqr(df["income"])
df["zscore_outlier"] = detect_outliers_zscore(df["income"])
print(df.head())

print("\nNumber of outliers (IQR):", df["iqr_outlier"].sum())
print("Number of outliers (Z-score):", df["zscore_outlier"].sum())