# -*- coding: utf-8 -*-
"""day 32

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXtFNrAQRQFpqjYwH6J3OJnh3LDDsGve
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("day32_relationships.csv")

plt.figure(figsize=(7,5))

sns.scatterplot(
    data=df,
    x="feature1",
    y="outcome",
    hue="segment",
    style="priority"
)

plt.title("Overall Relationship")
plt.show()