# -*- coding: utf-8 -*-
"""Day 8 Activity: Duplicates Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U3I2BUEZ7M_z-2HIlKJuJ6aWeXPNHk1y
"""

import pandas as pd

rows = [
    {"user": "U1", "day": "2024-01-01", "product": "A", "clicked": 1},
    {"user": "U1", "day": "2024-01-01", "product": "A", "clicked": 1},
    {"user": "U1", "day": "2024-01-01", "product": "B", "clicked": 0},
    {"user": "U2", "day": "2024-01-02", "product": "A", "clicked": 1},
]

df = pd.DataFrame(rows)

df_no_duplicates = df.drop_duplicates()

df_unique = df_no_duplicates.drop_duplicates(subset=["user", "day", "product"])

user_features = df_unique.groupby("user").agg(
    event_count=("product", "count"),
    ever_clicked=("clicked", "max")
).reset_index()

print(df_unique)
print(user_features)