# -*- coding: utf-8 -*-
"""Day 6 Activity: Missing Values Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lFLYxApaQMmHZh8YALt1ldhBYerytjwP
"""

import pandas as pd
import numpy as np

raw = {
    "age": [25, "N/A", 40, 33, "?"],
    "income": [50000, 60000, None, "unknown", 80000],
    "churned": [0, 1, 0, 1, 0],
}

df = pd.DataFrame(raw)

tokens = ["N/A", "NA", "not reported", "unknown", "?"]
df = df.replace(tokens, np.nan)

print(df)

print(df.isna().mean() * 100)

version_a = df.dropna(subset=["age", "income"])

print(version_a)

df["age"] = pd.to_numeric(df["age"])
df["income"] = pd.to_numeric(df["income"])

df["age_missing"] = df["age"].isna().astype(int)
df["income_missing"] = df["income"].isna().astype(int)

df["age"] = df["age"].fillna(df["age"].median())
df["income"] = df["income"].fillna(df["income"].median())

print(df)