# -*- coding: utf-8 -*-
"""homework 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-k0sIeAON6FooNgbYmcUwQ7mA4m-YyS
"""

import numpy as np
import pandas as pd

df = pd.DataFrame({
    "age": [25, "N/A", 40, 33, "?"],
    "income": [50000, 60000, None, "unknown", 80000],
    "churned": [0, 1, 0, 1, 0],
})

"""1) Normalize missing tokens → NaN"""

df = df.replace(["N/A","NA","not reported","unknown","?"], np.nan)

df["age"] = pd.to_numeric(df["age"])
df["income"] = pd.to_numeric(df["income"])

"""2) Missing summary (عمود + صف)"""

print("Missing % per column:")
print(df.isna().mean() * 100)

print("\nMissing % per row:")
print(df.isna().mean(axis=1) * 100)

"""3) Version A (Drop)"""

A = df.dropna(subset=["age","income"])
print(A)

"""4) Version B (Impute + Indicators)"""

B = df.copy()

B["age_missing"] = B["age"].isna().astype(int)
B["income_missing"] = B["income"].isna().astype(int)

B["age"] = B["age"].fillna(B["age"].median())
B["income"] = B["income"].fillna(B["income"].median())

print(B)

"""5) Compare simple metrics"""

print("A mean age:", A["age"].mean())
print("B mean age:", B["age"].mean())

print("A mean income:", A["income"].mean())
print("B mean income:", B["income"].mean())