# -*- coding: utf-8 -*-
"""Linear Regression-Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9DmYjHhZ27vV4OrZD-5lZFKxB5ashK9
"""

import pandas as pd
import numpy as np

# Create the DataFrame
df = pd.DataFrame({
    "age": [25, "unknown", 30, "NA", 40],
    "salary": ["5000", "N/A", "?", "7000", "not reported"],
    "city": ["Riyadh", "Jeddah", "unknown", "Dammam", "Riyadh"]
})
missing_tokens = ["N/A", "NA", "not reported", "unknown", "?"]
df_clean = df.replace(missing_tokens, np.nan)
missing_percentage = df_clean.isna().mean() * 100
print(df_clean)
print(missing_percentage)
# The salary column would be the most harmful because it has the highest percentage
# of missing values and is an important numerical feature for models.